### PR TITLE
Replaced sha1 algorithm with OpenSSL sha1 algorithm

### PR DESCRIPTION
**Pull request by BlueCannonBall**

### CODE REVIEW

**Comment by Matheus28** [comment]
Due to my shitty code, I do assume sha1::toHexString exists in a different project that uses ws28. I'll look into merging this later, though.

**Comment by BlueCannonBall** [comment]
Okay, I added `sha1::toHexString` back.

**Comment by BlueCannonBall** [comment]
> I'll look into merging this later, though.

@Matheus28 Any progress on this?

**Comment by Matheus28** [comment]
Not high on my priority list right now, I'd need to see if it impacts any of my projects, etc.

**Comment by BlueCannonBall** [comment]
Any reason why this hasn't been merged yet? It's been a while.

**Comment by Matheus28** [comment]
It's been merged by pulling some changes from another repo. Thanks.

**Pull request closed without merging**
